name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - testing-neural-network
trigger:
  branches:
    include:
      - testing-neural-network

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-thankful-river-0c7d2cc1e-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: UseNode@1
    inputs:
      version: '18.x'
  - script: |
      echo "##vso[task.setvariable variable=NEXT_PUBLIC_OPEN_AI_API]$(NEXT_PUBLIC_OPEN_AI_API)"
      echo "##vso[task.setvariable variable=NEXT_PUBLIC_ASSISTANT_ID]$(NEXT_PUBLIC_ASSISTANT_ID)"
      npm install
      npm run build
    displayName: 'Build Application'
    env:
      NODE_VERSION: 18.17.0
      NEXT_PUBLIC_OPEN_AI_API: $(NEXT_PUBLIC_OPEN_AI_API)
      NEXT_PUBLIC_ASSISTANT_ID: $(NEXT_PUBLIC_ASSISTANT_ID)
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_RIVER_0C7D2CC1E)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "" # Built app content directory - optional
###### End of Repository/Build Configurations ######
